// ActionTypes
export default {
    SET_INIT_DATA: 'SET_INIT_DATA',
    SORT_ROWS_BY: 'SORT_ROWS_BY',
    HANDLE_OPEN_EDIT: 'HANDLE_OPEN_EDIT',
    HANDLE_OPEN_DELETE: 'HANDLE_OPEN_DELETE',
    SET_SEARCH_DATA: 'SET_SEARCH_DATA'
}
